# Generated by Django 5.1.7 on 2025-04-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pofile_picture',
            new_name='profile_picture',
        ),
    ]
