# Generated by Django 5.1.6 on 2025-02-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_book_author_alter_librarian_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='books',
            new_name='book',
        ),
    ]
